 name: workshop-env
 channels:
   - conda-forge
 dependencies:
   - python=3.9.1
   - ipython=8.0.1
   - jupyterlab
   - ipykernel
   - pytest
   - xarray
   - netcdf4
   - numexpr
   - jax
   - numba
   - joblib
   - dask
   - altair
